name = "oficios-counter"
main = "src/index.js"
compatibility_date = "2026-06-26"

[durable_objects]
bindings = [
  { name = "COUNTER", class_name = "Counter" }
]

[[migrations]]
tag = "v1"
new_classes = ["Counter"]
